run:
  timeout: 2m

linters-settings:
  cyclop:
    max-complexity: 16
    package-average: 0.5
  lll:
    line-length: 120
    tab-width: 1


linters:
  enable:
    - bodyclose
    - cyclop
    - gochecknoglobals
    - goimports
    - gosec
    - lll
    - nilerr
    - noctx
    - sqlclosecheck
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - module
    - performance
    - sql
    - style
    - unused
  fast: true
