name: golangci-lint
on:
  pull_request:

concurrency:
  group: linter-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Mod Fix for Skynet Deps
        run: make mod-fix
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          args: --config golangci.yaml
