name: OCI Distribution Spec

on:
  pull_request:

jobs:
  content-management:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          PGUSER: postgres
          POSTGRES_DB: open_registry
          POSTGRES_PASSWORD: Qwerty@123
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Install Migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          sudo netstat -tulnp
      - name: Setup PostgreSQL Database
        run: |
          IP=`hostname -I | awk '{print $1}'`
          POSTGRESQL_URL=postgres://$PGUSER:$PGPASSWORD@$IP:5432/$PGDATABASE?sslmode=disable
          migrate -database ${POSTGRESQL_URL} -path db/migrations up
        env:
           PGDATABASE: open_registry
           PGPASSWORD: Qwerty@123
           PGUSER: postgres
      - name: start distribution server
        run: |
          IP=`hostname -I | awk '{print $1}'`
          echo "IP=$IP" >> $GITHUB_ENV
          echo "OCI_ROOT_URL=http://$IP:5000" >> $GITHUB_ENV
          DISTRIBUTION_REF="local-distribution:v$(date +%Y%m%d%H%M%S)"
          docker build -f ./Dockerfile -t "${DISTRIBUTION_REF}" .
          sed -in "s/OPEN_REGISTRY_ENVIRONMENT=local/OPEN_REGISTRY_ENVIRONMENT=ci/g" env-vars.example
          echo CI_SYS_ADDR=$IP:5000 >> env-vars.example
          docker run --rm -p 5000:5000 --env-file ./env-vars.example -e REGISTRY_STORAGE_DELETE_ENABLED=true -d "${DISTRIBUTION_REF}"
          sleep 5
          curl -XPOST -d ${{ secrets.OPENREGISTRY_SIGNUP_PAYLOAD }} "http://${IP}:5000/auth/signup"
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@v1.0.1
        env:
          OCI_ROOT_URL: ${{ env.OCI_ROOT_URL }}
          OCI_USERNAME: ${{ secrets.OPENREGISTRY_USERNAME }}
          OCI_PASSWORD: ${{ secrets.OPENREGISTRY_PASSWORD }}
          OCI_NAMESPACE: ${{ secrets.OPENREGISTRY_USERNAME }}/distribution-test
          OCI_TEST_CONTENT_MANAGEMENT: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
          OCI_CROSSMOUNT_NAMESPACE: ${{secrets.OPENREGISTRY_USERNAME}}/distribution-cross-mount
          OCI_DEBUG: 0
          OCI_DELETE_MANIFEST_BEFORE_BLOBS: 0
      - run: mkdir -p .out/ && mv {report.html,junit.xml} .out/
        if: always()
      - name: Upload test results zip as build artifact
        uses: actions/upload-artifact@v1
        with:
          name: oci-test-results-${{ github.sha }}
          path: .out/
        if: always()
